
variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
    - release

release:


    image: mcr.microsoft.com/dotnet/core/sdk:3.0

    stage: release
    #only:
    #    - /^release-.*$/

    before_script:
        - dotnet restore RabbitCommunicationLib/
        - dotnet restore SteamworksCommunicator/

    script:
        - dotnet publish SteamworksCommunicator/ -c Release -o out -r win-x64

        
    artifacts:
        paths:
            - out

